### ISSUE TITLE
Design the user interface for the initial assessment.

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/ss23-talk-a-palooza#10]

**Comment by Camilagraciac** [comment]
First draft: 

![Image](https://github.com/TechLabs-Berlin/ss23-talk-a-palooza/assets/134846800/3f736374-62f6-49d0-94f1-52c8627b1838)

**Comment by Camilagraciac** [comment]
https://www.figma.com/proto/e04DLsVxMRcCBD2USBA0UT/Talk-a-Palooza-Design-System?type=design&node-id=312-5465&t=K63yE7UJ4gwfzMXe-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=312%3A5465&show-proto-sidebar=1
