### ISSUE TITLE
Create Prototype in Figma + user test

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/ss23-talk-a-palooza#16]

**Comment by Camilagraciac** [comment]
Exercise Figma Prototype: 
[[https://www.figma.com/proto/e04DLsVxMRcCBD2USBA0UT/Talk-a-Palooza-Design-System?type=design&node-id=271-1290&t=lCPPCZIojK8yutL2-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=271%3A1290](url)](https://www.figma.com/proto/e04DLsVxMRcCBD2USBA0UT/Talk-a-Palooza-Design-System?type=design&node-id=391-46367&t=ShGC2jGWfSLCDWFn-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=391%3A46367)

**Comment by Camilagraciac** [comment]
.

**Comment by Camilagraciac** [comment]
User Test: https://42qei34afqy.typeform.com/to/s3el48Bo
