### ISSUE TITLE
Design the user interface for the personalized exercises section.

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/ss23-talk-a-palooza#17]

**Comment by Camilagraciac** [comment]
**Comment**

Excersice: 

- Two or three words mixed per screen so the children don’t get frustrated when not pronouncing a word correctly, the sound will appear again not showing any “bad” sign, and as a part of the flow. The AI should be able to get the well and wrong-pronounced words and continue showing the ones that present more difficulty to the child. 

- Rewards will be added, if possible, in the future in a song-video (or link to video) format. Further, we could add games, different interactive videos, and songs. 

- Filters can be added when the child says a word, so they are motivated and engaged.

**Comment by Camilagraciac** [comment]
.

**Comment by Camilagraciac** [comment]
[User interface for the personalized exercises section (3).pdf](https://github.com/TechLabs-Berlin/ss23-talk-a-palooza/files/12451757/User.interface.for.the.personalized.exercises.section.3.pdf)

**Comment by Camilagraciac** [comment]
![Image](https://github.com/TechLabs-Berlin/ss23-talk-a-palooza/assets/134846800/7ac29d6c-c71e-4389-8b88-ae734a0ba505)
