### ISSUE TITLE
Design a user-friendly dashboard for parents to track their child's progress.

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/ss23-talk-a-palooza#21]

**Comment by Camilagraciac** [comment]
Still need to be adjusted with the real information/data we are going to be able to provide in the demo phase.

![Image](https://github.com/TechLabs-Berlin/ss23-talk-a-palooza/assets/134846800/74fbcfb8-da10-43b5-b628-ab032fe1a633)
