### ISSUE TITLE
Create User Flows & interface design (layout level)

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/ss23-talk-a-palooza#33]

**Comment by Camilagraciac** [comment]
Wireflow document added. 

**Comments:** 

Splash Screen - Log in - Register
Sign up:  Tutorial
Initial Assesment:  Results
Exercise:  Reward
Main Menu: My own path and Catalog (low priority)
Dashboard: Summary - Statistics - Settings


[WireFlow.pdf](https://github.com/TechLabs-Berlin/ss23-talk-a-palooza/files/12447624/WireFlow.pdf)

**Comment by Camilagraciac** [comment]
The view is LANDSCAPE
